name: Web Admin CI/CD

on:
  push:
    branches:
      - webAdminBranch  # Adjust to your target branch
  workflow_dispatch:  # Allows manual triggering from GitHub Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: webAdminBranch  # Adjust to the branch you want to use (develop or webAdminBranch)

      # List files to verify directory structure
      - name: List files
        run: ls -la

      # Install dependencies
      - name: Install dependencies
        run: npm install

      - name: Set up Chrome
        run: sudo apt-get install -y google-chrome-stable

      # Run tests (optional)
      - name: Run tests
        run: npm run test:selenium
        
