name: Web Admin CI/CD

on:
  push:
    branches:
      - webAdminBranch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: webAdminBranch  # Adjust to the branch you want to use (develop or webAdminBranch)

      # Cache Node modules
      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Install Chrome
      - name: Install Google Chrome
        run: sudo apt-get install -y google-chrome-stable

      # Install ChromeDriver matching Chrome version
      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome-stable --version | grep -oP '\d+\.\d+\.\d+')
          npm install chromedriver@$CHROME_VERSION
          chmod +x node_modules/.bin/chromedriver

      # Start Xvfb for headless testing
      - name: Start Xvfb
        run: |
          sudo apt-get install -y xvfb
          Xvfb :99 & export DISPLAY=:99

      # Run Selenium tests in headless mode
      - name: Run Selenium tests
        env:
          DISPLAY: :99
        run: |
          google-chrome-stable --version
          node_modules/.bin/chromedriver --version
          npm run test:selenium -- --headless

      # Debug step: Print log files
      - name: Print Chrome logs
        run: |
          if [ -f /var/log/google-chrome/chrome_debug.log ]; then
            cat /var/log/google-chrome/chrome_debug.log
          fi
