name: Android CI

on:
  push:
    branches: [ "appBranch" ]
  pull_request:
    branches: [ "appBranch" ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Tests
        run: ./gradlew test

      - name: Create Lint Baseline
        run: ./gradlew updateLintBaseline

      - name: Run Lint
        run: ./gradlew lint -Dlint.baselines.continue=true

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: app/build/reports/

      - name: Generate Debug APK
        run: ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

  publish:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: appBranch

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Prepare artifact directory
        run: |
          mkdir -p artifact
          cp -r artifacts/test-reports/* artifact/ || true
          cp -r artifacts/app-debug/* artifact/ || true
        
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az extension add --name azure-devops
      
      - name: Azure DevOps Login
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        run: echo $AZURE_DEVOPS_PAT | az devops login
      
      - name: Azure DevOps Artifact Upload
        env:
          AZURE_DEVOPS_ORG: ${{ secrets.AZURE_DEVOPS_ORG }}
          AZURE_DEVOPS_PROJECT: ${{ secrets.AZURE_DEVOPS_PROJECT }}
        run: |
          # Configure Azure DevOps CLI
          az devops configure --defaults organization="$AZURE_DEVOPS_ORG" project="$AZURE_DEVOPS_PROJECT"
          
          # List contents of artifact directory
          echo "Contents of artifact directory:"
          ls -la artifact/
          
          # Create and publish artifact
          az artifacts universal publish \
            --organization "$AZURE_DEVOPS_ORG" \
            --project "$AZURE_DEVOPS_PROJECT" \
            --scope project \
            --feed "KubaduMobileArtifacts" \
            --name "android-app-build" \
            --version "$GITHUB_RUN_NUMBER.0.0" \
            --path artifact \
            --description "Kubadu Services Mobile App Build #$GITHUB_RUN_NUMBER - Includes APK, test reports, and lint results"
