name: Kotlin App CI/CD

on:
  push:
    branches:
      - appBranch
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: appBranch  # Adjust to the branch you want to use (develop or webAdminBranch)

      # Step 3: Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}

      # Step 4: Build the app
      - name: Build with Gradle
        run: ./gradlew build

      # Step 5: Run tests
      - name: Run tests
        run: ./gradlew test

      # Step 6: Upload build artifacts (APK)
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
