name: Web User CI/CD

on:
  push:
    branches:
      - master  # Adjust to your target branch
  workflow_dispatch:  # Allows manual triggering from GitHub Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: master  # Adjust to the branch you want to use

      # List files to verify directory structure
      - name: List files
        run: ls -la

      # Cache Node modules
      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests (optional)
      - name: Run tests
        run: npm test

      # Upload test artifacts
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            test/screenshots
            test-results
            npm-debug.log
          retention-days: 7

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az extension add --name azure-devops

      - name: Azure DevOps Login
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        run: echo $AZURE_DEVOPS_PAT | az devops login

      - name: Azure DevOps Artifact Upload
        env:
          AZURE_DEVOPS_ORG: ${{ secrets.AZURE_DEVOPS_ORG }}
          AZURE_DEVOPS_PROJECT: ${{ secrets.AZURE_DEVOPS_PROJECT }}
        run: |
          # Configure Azure DevOps CLI
          az devops configure --defaults organization="$AZURE_DEVOPS_ORG" project="$AZURE_DEVOPS_PROJECT"
          
          # Create and publish artifact
          az artifacts universal publish \
            --organization "$AZURE_DEVOPS_ORG" \
            --project "$AZURE_DEVOPS_PROJECT" \
            --scope project \
            --feed "WebUserTests" \
            --name "test-results" \
            --version "$GITHUB_RUN_NUMBER" \
            --path artifact \
            --description "Test Results from GitHub Actions Run #$GITHUB_RUN_NUMBER"
