name: Web Admin CI/CD

on:
  push:
    branches:
      - webAdminBranch
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "admin-pages"
  cancel-in-progress: true

env:
  BASE_PATH: '/admin'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: webAdminBranch

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install
          npm install -g mocha
          npm install -g chromedriver

      - name: Set up test environment
        run: |
          mkdir -p test/screenshots
          chmod -R 777 test/screenshots
          
          # Start ChromeDriver
          chromedriver --port=4444 &
          sleep 3  # Give ChromeDriver time to start

      - name: Start Xvfb
        run: |
          sudo apt-get install -y xvfb
          Xvfb :99 &
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Run Selenium tests
        env:
          CI: true
          NODE_ENV: test
          DISPLAY: :99
          SELENIUM_REMOTE_URL: "http://localhost:4444"
        run: |
          echo "Chrome version:"
          google-chrome --version
          echo "ChromeDriver version:"
          chromedriver --version
          
          echo "Running Selenium tests..."
          npx mocha --timeout 60000 --retries 2 test/*.selenium.test.js

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            test/screenshots
            test-results
            selenium-debug.log
          retention-days: 7

      - name: Upload test logs on failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-logs
          path: |
            npm-debug.log
            selenium-debug.log
            test/screenshots
            /var/log/google-chrome/chrome_debug.log
          retention-days: 7

      - name: Print Chrome logs
        if: always()
        run: |
          if [ -f /var/log/google-chrome/chrome_debug.log ]; then
            cat /var/log/google-chrome/chrome_debug.log
          fi

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: webAdminBranch
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build with base path
        run: |
          # Add any build commands here if needed
          echo "Building admin site with base path: ${{ env.BASE_PATH }}"
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public_html
          
  deploy:
    needs: build
    environment:
      name: admin-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          path: ./public_html
          
  publish:
    needs: [test, deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: webAdminBranch

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Prepare artifact directory
        run: |
          mkdir -p artifact
          cp -r artifacts/test-results/* artifact/ || true
          cp -r artifacts/test-logs/* artifact/ || true
        
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az extension add --name azure-devops
      
      - name: Azure DevOps Login
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        run: echo $AZURE_DEVOPS_PAT | az devops login
      
      - name: Azure DevOps Artifact Upload
        env:
          AZURE_DEVOPS_ORG: ${{ secrets.AZURE_DEVOPS_ORG }}
          AZURE_DEVOPS_PROJECT: ${{ secrets.AZURE_DEVOPS_PROJECT }}
        run: |
          # Configure Azure DevOps CLI
          az devops configure --defaults organization="$AZURE_DEVOPS_ORG" project="$AZURE_DEVOPS_PROJECT"
          
          # List contents of artifact directory
          echo "Contents of artifact directory:"
          ls -la artifact/
          
          # Create and publish artifact
          az artifacts universal publish \
            --organization "$AZURE_DEVOPS_ORG" \
            --project "$AZURE_DEVOPS_PROJECT" \
            --scope project \
            --feed "WebAdminTests" \
            --name "selenium-test-results" \
            --version "$GITHUB_RUN_NUMBER.0.0" \
            --path artifact \
            --description "Selenium Test Results from GitHub Actions Run #$GITHUB_RUN_NUMBER"
